blueprint:
  name: "Systemair SAVE VTR 250 Advanced Control for Oslo Climate"
  description: "Dynamically control the Systemair SAVE VTR 250 ventilation system based on multiple sensors and 3-day temperature average, optimized for Oslo's climate."
  domain: automation
  input:
    bathroom_humidity_sensor:
      name: Bathroom Humidity Sensor
      selector:
        entity:
          domain: sensor
          device_class: humidity
    bedroom_co2_sensor:
      name: Bedroom CO2 Sensor
      selector:
        entity:
          domain: sensor
          device_class: carbon_dioxide
    living_room_co2_sensor:
      name: Living Room CO2 Sensor
      selector:
        entity:
          domain: sensor
          device_class: carbon_dioxide

variables:
  cooling_threshold: 22
  heating_threshold: 20
  humidity_threshold: 60
  co2_threshold: 800
  summer_temp_threshold: 15  # Average temperature above this is considered summer mode

trigger:
  - platform: state
    entity_id: 
      - sensor.systemair_save_vtr_250_outdoor_air_temperature
      - sensor.systemair_save_vtr_250_extract_air_temperature
      - sensor.systemair_save_vtr_250_supply_air_temperature
      - sensor.systemair_save_vtr_250_relative_humidity
      - sensor.multisensor_bad_humidity
      - sensor.multisensor_henny_temperature
      - sensor.multisensor_nora_temperature
      - sensor.multisensor_soverom_temperature
      - sensor.airthings_soverommet_karbondioksid
      - sensor.airthings_stua_karbondioksid
  - platform: state
    entity_id: sensor.systemair_vtr_250_active_user_mode
  - platform: time_pattern
    minutes: "/5"

action:
  - variables:
      outdoor_temp: "{{ states('sensor.systemair_save_vtr_250_outdoor_air_temperature') | float }}"
      extract_temp: "{{ states('sensor.systemair_save_vtr_250_extract_air_temperature') | float }}"
      supply_temp: "{{ states('sensor.systemair_save_vtr_250_supply_air_temperature') | float }}"
      current_humidity: "{{ states('sensor.systemair_save_vtr_250_relative_humidity') | float }}"
      bathroom_humidity: "{{ states(bathroom_humidity_sensor) | float }}"
      bedroom_co2: "{{ states(bedroom_co2_sensor) | float }}"
      living_room_co2: "{{ states(living_room_co2_sensor) | float }}"
      active_mode: "{{ states('sensor.systemair_vtr_250_active_user_mode') }}"
      max_room_temp: "{{ [states('sensor.multisensor_henny_temperature') | float, 
                          states('sensor.multisensor_nora_temperature') | float, 
                          states('sensor.multisensor_soverom_temperature') | float] | max }}"
      temp_3day_avg: "{{ state_attr('sensor.systemair_save_vtr_250_outdoor_air_temperature', '3day_avg') | default(outdoor_temp) }}"
      is_summer: "{{ temp_3day_avg > summer_temp_threshold }}"

  - choose:
      # Auto mode (assuming "Manuell" is the auto mode)
      - conditions:
          - condition: template
            value_template: "{{ active_mode == 'Manuell' }}"
        sequence:
          - choose:
              # Summer operation
              - conditions:
                  - condition: template
                    value_template: "{{ is_summer }}"
                sequence:
                  - choose:
                      # Cooling needed
                      - conditions:
                          - condition: numeric_state
                            entity_id: 
                              - sensor.multisensor_henny_temperature
                              - sensor.multisensor_nora_temperature
                              - sensor.multisensor_soverom_temperature
                            above: "{{ cooling_threshold }}"
                          - condition: template
                            value_template: "{{ outdoor_temp < max_room_temp }}"
                        sequence:
                          - service: select.select_option
                            target:
                              entity_id: select.systemair_save_vtr_250_airflow_setpoint
                            data:
                              option: "Høy"
                          - service: switch.turn_on
                            target:
                              entity_id: switch.systemair_save_vtr_250_free_cooling
                      # Reduce airflow when outside temp is higher
                      - conditions:
                          - condition: template
                            value_template: "{{ outdoor_temp > max_room_temp }}"
                        sequence:
                          - service: select.select_option
                            target:
                              entity_id: select.systemair_save_vtr_250_airflow_setpoint
                            data:
                              option: "Lav"
                          - service: switch.turn_off
                            target:
                              entity_id: switch.systemair_save_vtr_250_free_cooling
              # Winter operation
              - conditions:
                  - condition: template
                    value_template: "{{ not is_summer }}"
                sequence:
                  - choose:
                      # Heating needed
                      - conditions:
                          - condition: numeric_state
                            entity_id: 
                              - sensor.multisensor_henny_temperature
                              - sensor.multisensor_nora_temperature
                              - sensor.multisensor_soverom_temperature
                            below: "{{ heating_threshold }}"
                        sequence:
                          - service: select.select_option
                            target:
                              entity_id: select.systemair_save_vtr_250_airflow_setpoint
                            data:
                              option: "Normal"
              # High CO2 (year-round)
              - conditions:
                  - condition: or
                    conditions:
                      - condition: numeric_state
                        entity_id: !input bedroom_co2_sensor
                        above: "{{ co2_threshold }}"
                      - condition: numeric_state
                        entity_id: !input living_room_co2_sensor
                        above: "{{ co2_threshold }}"
                sequence:
                  - service: select.select_option
                    target:
                      entity_id: select.systemair_save_vtr_250_airflow_setpoint
                    data:
                      option: "Høy"
              # High humidity in bathroom (year-round)
              - conditions:
                  - condition: numeric_state
                    entity_id: !input bathroom_humidity_sensor
                    above: "{{ humidity_threshold }}"
                sequence:
                  - service: select.select_option
                    target:
                      entity_id: select.systemair_save_vtr_250_airflow_setpoint
                    data:
                      option: "Høy"
            default:
              - service: select.select_option
                target:
                  entity_id: select.systemair_save_vtr_250_airflow_setpoint
                data:
                  option: "Normal"

      # Other modes
      - conditions:
          - condition: template
            value_template: "{{ active_mode != 'Manuell' }}"
        sequence:
          - service: select.select_option
            target:
              entity_id: select.systemair_save_vtr_250_change_user_mode
            data:
              option: "{{ active_mode }}"

  # Adjust temperature setpoint based on season and outdoor temperature
  - service: number.set_value
    target:
      entity_id: number.systemair_save_vtr_250_temperature_setpoint
    data:
      value: >
        {% if is_summer %}
          {{ [([outdoor_temp - 2, cooling_threshold] | min, 30) | min, 12] | max }}
        {% else %}
          {{ [([outdoor_temp + 2, heating_threshold] | max, 30) | min, 12] | max }}
        {% endif %}

  # Enable ECO mode when conditions are suitable (more conservative in winter)
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: numeric_state
                entity_id: sensor.systemair_save_vtr_250_outdoor_air_temperature
                below: "{{ extract_temp - (2 if is_summer else 5) }}"
              - condition: numeric_state
                entity_id: sensor.systemair_save_vtr_250_relative_humidity
                below: 70
              - condition: numeric_state
                entity_id: 
                  - !input bedroom_co2_sensor
                  - !input living_room_co2_sensor
                below: "{{ co2_threshold - 100 }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.systemair_save_vtr_250_eco_mode
    default:
      - service: switch.turn_off
        target:
          entity_id: switch.systemair_save_vtr_250_eco_mode

  - service: logbook.log
    data:
      name: "Systemair SAVE VTR 250"
      message: >
        Mode: {{ active_mode }}, Season: {{ 'Summer' if is_summer else 'Winter' }},
        3-day Avg: {{ temp_3day_avg }}°C, Outdoor: {{ outdoor_temp }}°C, 
        Extract: {{ extract_temp }}°C, Supply: {{ supply_temp }}°C, 
        Max Room: {{ max_room_temp }}°C, System Humidity: {{ current_humidity }}%, 
        Bathroom Humidity: {{ bathroom_humidity }}%, 
        Bedroom CO2: {{ bedroom_co2 }} ppm, Living Room CO2: {{ living_room_co2 }} ppm
